UniversityStudentsApp/Models/Teacher.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace UniversityStudentsApp.Models
{
    public class Teacher
    {
        [Required]
        public int Id { get; set; }

        [StringLength(50,MinimumLength =3)]
        [Required]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [StringLength(50, MinimumLength = 3)]
        [Required]
        [Display(Name = "Last Name")]

        public string LastName { get; set; }

        [StringLength(50, MinimumLength = 3)]
        public string Degree { get; set; }

        [StringLength(25, MinimumLength = 3)]
        public string AcademicRank { get; set; }

        [StringLength(10, MinimumLength = 1)]
        public string OfficeNumber { get; set; }

        public DateTime HireDate { get; set; }

        [Display(Name = "Professor Full Name")]
        public string FullName
        {
            get { return String.Format("{0} {1}", FirstName, LastName); }
        }

        public ICollection<Course> FirstTeacherCourses { get; set; }

        public ICollection<Course> SecondTeacherCourses { get; set; }




    }
}

UniversityStudentsApp/Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using UniversityStudentsApp.Data;
using UniversityStudentsApp.Models;

namespace UniversityStudentsApp.Controllers
{
    public class CoursesController : Controller
    {
        private readonly UniversityStudentsAppContext _context;

        public CoursesController(UniversityStudentsAppContext context)
        {
            _context = context;
        }

        // GET: Courses
        public async Task<IActionResult> Index(string searchTitle, string searchSemester, string searchProgramme)
        {
            //var universityStudentsAppContext = _context.Courses.Include(c => c.FirstTeacher).Include(c => c.SecondTeacher);
            // return View(await universityStudentsAppContext.ToListAsync());

            ViewData["CurrentFilter8"] = searchTitle;
            ViewData["CurrentFilter9"] = searchSemester;
            ViewData["CurrentFilter10"] = searchProgramme;

            var courses = from s in _context.Courses
                          select s;

            if(!String.IsNullOrEmpty(searchTitle))
            {
                courses = courses.Where(s => s.Title.Contains(searchTitle));
            }
            if (!String.IsNullOrEmpty(searchSemester))
            {
                courses = courses.Where(s => s.Title.Contains(searchSemester));
            }
            if (!String.IsNullOrEmpty(searchProgramme))
            {
                courses = courses.Where(s => s.Title.Contains(searchProgramme));
            }

            courses = courses.Include(m => m.FirstTeacher);
            courses = courses.Include(m => m.SecondTeacher);
            courses = courses.Include(m => m.Students);

            return View(await courses.AsNoTracking().ToListAsync());
        }

        // GET: Courses/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Courses
                .Include(c => c.FirstTeacher)
                .Include(c => c.SecondTeacher)
                .Include(c => c.Students).ThenInclude(c => c.Student)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        // GET: Courses/Create
        public IActionResult Create()
        {
            ViewData["FirstTeacherId"] = new SelectList(_context.Teacher, "Id", "FullName");
            ViewData["SecondTeacherId"] = new SelectList(_context.Teacher, "Id", "FullName");
            return View();
        }

        // POST: Courses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Credits,Semester,Programme,EducationLevel,FirstTeacherId,SecondTeacherId")] Course course)
        {
            if (ModelState.IsValid)
            {
                _context.Add(course);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["FirstTeacherId"] = new SelectList(_context.Teacher, "Id", "FulltName", course.FirstTeacherId);
            ViewData["SecondTeacherId"] = new SelectList(_context.Teacher, "Id", "FullName", course.SecondTeacherId);
            return View(course);
        }

        // GET: Courses/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Courses.FindAsync(id);
            if (course == null)
            {
                return NotFound();
            }

            ViewData["FirstTeacherId"] = new SelectList(_context.Teacher, "Id", "FullName", course.FirstTeacherId);
            ViewData["SecondTeacherId"] = new SelectList(_context.Teacher, "Id", "FullName", course.SecondTeacherId);
            return View(course);
        }

        // POST: Courses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Credits,Semester,Programme,EducationLevel,FirstTeacherId,SecondTeacherId")] Course course)
        {
            if (id != course.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(course);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CourseExists(course.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["FirstTeacherId"] = new SelectList(_context.Teacher, "Id", "FullName", course.FirstTeacherId);
            ViewData["SecondTeacherId"] = new SelectList(_context.Teacher, "Id", "FullName", course.SecondTeacherId);
            return View(course);
        }

        // GET: Courses/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Courses
                .Include(c => c.FirstTeacher)
                .Include(c => c.SecondTeacher)
                .Include(c => c.Students).ThenInclude(c => c.Student)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        // POST: Courses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var course = await _context.Courses.FindAsync(id);
            _context.Courses.Remove(course);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CourseExists(int id)
        {
            return _context.Courses.Any(e => e.Id == id);
        }

        public async Task<IActionResult> GetCoursеById (int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Courses
                .Include(c => c.FirstTeacher)
                .Include(c => c.SecondTeacher)
                .Include(c => c.Students)
                .FirstOrDefaultAsync(c => c.Id == id);

            return View(course);
        }
    }
}

UniversityStudentsApp/Controllers/TeachersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using UniversityStudentsApp.Data;
using UniversityStudentsApp.Models;

namespace UniversityStudentsApp.Controllers
{
    public class TeachersController : Controller
    {
        private readonly UniversityStudentsAppContext _context;

        public TeachersController(UniversityStudentsAppContext context)
        {
            _context = context;
        }

        // GET: Teachers
        public async Task<IActionResult> Index(string searchFirstName, string searchLastName, string searchDegree, string searchARank)
        {
            // return View(await _context.Teacher.ToListAsync());
            ViewData["CurrentFilter4"] = searchFirstName;
            ViewData["CurrentFilter5"] = searchLastName;
            ViewData["CurrentFilter6"] = searchDegree;
            ViewData["CurrentFilter7"] = searchARank;

            var teachers = from s in _context.Teacher
                           select s;

            if (!String.IsNullOrEmpty(searchFirstName))
            {
                teachers = teachers.Where(s => s.FirstName.Contains(searchFirstName));
            }
            if (!String.IsNullOrEmpty(searchLastName))
            {
                teachers = teachers.Where(s => s.LastName.Contains(searchLastName));

            }
            if (!String.IsNullOrEmpty(searchDegree))
            {
                teachers = teachers.Where(s => s.Degree.Contains(searchDegree));
            }
            if (!String.IsNullOrEmpty(searchARank))
            {
                teachers = teachers.Where(s => s.AcademicRank.Contains(searchARank));
            }

            teachers = teachers.Include(m => m.FirstTeacherCourses)
                .Include(m => m.SecondTeacherCourses);


            return View(await teachers.AsNoTracking().ToListAsync());
        }
            // GET: Teachers/Details/5
            public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var teacher = await _context.Teacher
                .Include(p => p.FirstTeacherCourses)
                .Include(p => p.SecondTeacherCourses)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (teacher == null)
            {
                return NotFound();
            }

            return View(teacher);
        }

        // GET: Teachers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Teachers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FirstName,LastName,Degree,AcademicRank,OfficeNumber,HireDate")] Teacher teacher)
        {
            if (ModelState.IsValid)
            {
                _context.Add(teacher);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(teacher);
        }

        // GET: Teachers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var teacher = await _context.Teacher.FindAsync(id);
            if (teacher == null)
            {
                return NotFound();
            }
            return View(teacher);
        }

        // POST: Teachers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FirstName,LastName,Degree,AcademicRank,OfficeNumber,HireDate")] Teacher teacher)
        {
            if (id != teacher.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(teacher);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TeacherExists(teacher.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(teacher);
        }

        // GET: Teachers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var teacher = await _context.Teacher
                .Include(p => p.FirstTeacherCourses)
                .Include(p => p.SecondTeacherCourses)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (teacher == null)
            {
                return NotFound();
            }

            return View(teacher);
        }

        // POST: Teachers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var teacher = await _context.Teacher.FindAsync(id);
            _context.Teacher.Remove(teacher);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TeacherExists(int id)
        {
            return _context.Teacher.Any(e => e.Id == id);
        }

        public async Task<IActionResult> GetTeacherById (int? id, int? courseId)
        {
            if(id == null)
            {
                return NotFound();
            }

            var teacher = await _context.Teacher
                .Include(p => p.FirstTeacherCourses)
                    .ThenInclude(p => p.Students).ThenInclude(p => p.Student)
                .Include(p => p.SecondTeacherCourses)
                    .ThenInclude(p => p.Students).ThenInclude(p => p.Student)
                .AsNoTracking()
                .FirstOrDefaultAsync(m => m.Id == id);

            return View(teacher);
        }
            
    }
}

UniversityStudentsApp/Views/Teachers/Create.cshtml
@model UniversityStudentsApp.Models.Teacher

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Teacher</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Degree" class="control-label"></label>
                <input asp-for="Degree" class="form-control" />
                <span asp-validation-for="Degree" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AcademicRank" class="control-label"></label>
                <input asp-for="AcademicRank" class="form-control" />
                <span asp-validation-for="AcademicRank" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OfficeNumber" class="control-label"></label>
                <input asp-for="OfficeNumber" class="form-control" />
                <span asp-validation-for="OfficeNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HireDate" class="control-label"></label>
                <input asp-for="HireDate" class="form-control" />
                <span asp-validation-for="HireDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

UniversityStudentsApp/Views/Teachers/Delete.cshtml
@model UniversityStudentsApp.Models.Teacher

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Teacher</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Degree)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Degree)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AcademicRank)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AcademicRank)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OfficeNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OfficeNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HireDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HireDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

UniversityStudentsApp/Views/Teachers/Details.cshtml
@model UniversityStudentsApp.Models.Teacher

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Teacher</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Degree)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Degree)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AcademicRank)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AcademicRank)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OfficeNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OfficeNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HireDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HireDate)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

UniversityStudentsApp/Views/Teachers/Edit.cshtml
@model UniversityStudentsApp.Models.Teacher

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Teacher</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Degree" class="control-label"></label>
                <input asp-for="Degree" class="form-control" />
                <span asp-validation-for="Degree" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AcademicRank" class="control-label"></label>
                <input asp-for="AcademicRank" class="form-control" />
                <span asp-validation-for="AcademicRank" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OfficeNumber" class="control-label"></label>
                <input asp-for="OfficeNumber" class="form-control" />
                <span asp-validation-for="OfficeNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HireDate" class="control-label"></label>
                <input asp-for="HireDate" class="form-control" />
                <span asp-validation-for="HireDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

UniversityStudentsApp/Views/Teachers/GetTeacherById.cshtml
@model UniversityStudentsApp.Models.Teacher
@{
    ViewData["Title"] = "GetTeacherById";
}

    <h1>@Html.DisplayFor(modelItem => modelItem.FullName)</h1>

<tabele class="table">
    <thead>
        <tr>
            <th> Courses </th>
            <th> Students </th>
        </tr>
    </thead>

    <tbody>
        @if (Model.FirstTeacherCourses != null)
        {
            @foreach (var course in Model.FirstTeacherCourses)
            {
                <tr>
                    <td>
                        @if (course.Id != 0)
                        {
                            string teacher = Html.DisplayFor(modelItem => modelItem.FirstName).ToString();
                            @Html.ActionLink(teacher, "GetTeacherById", new { courseId = course.Id });
                            @course.Id

                            <a asp-controller="Enrollments" asp-action="GetStudentsByCourse" asp-route-id="@course.Id">
                                @course.Title
                            </a> <br />
                        }
                    </td>
                    <td>
                        @foreach (var student in course.Students)
                        {
                            @student.Student.FullName
                            <br />
                        }
                    </td>
                </tr>
            }
        }

        @if (Model.SecondTeacherCourses != null)
        {
            @foreach (var course in Model.SecondTeacherCourses)
            {
                <tr>
                    <td>
                        @if (course.Id != 0)
                        {
                            string teacher = Html.DisplayFor(modelItem => modelItem.FirstName).ToString();
                            @Html.ActionLink(teacher, "GetTeacherById", new { courseId = course.Id });
                            @course.Id

                            <a asp-controller="Enrollments" asp-action="GetStudentsByCourse" asp-route-id="@course.Id">
                                @course.Title
                            </a> <br />
                        }
                    </td>
                    <td>
                        @foreach (var student in course.Students)
                        {
                            @student.Student.FullName
                            <br />
                        }
                    </td>
                </tr>
            }
        }


    </tbody>
</tabele>

UniversityStudentsApp/Views/Teachers/Index.cshtml
@model IEnumerable<UniversityStudentsApp.Models.Teacher>

@{
    ViewData["Title"] = "Index";
}

<h1>Professors</h1>
<br />
<form asp-controller="Teachers" asp-action="Index" method="get">
    <p>
        First Name: <input type="text" name="searchFirstName" value="@ViewData["CurrentFilter4"]" />
        Last Name: <input type="text" name="searchLastName" value="@ViewData["CurrentFilter5"]" />
        Degree:  <input type="text" name="searchDegree" value="@ViewData["CurrentFilter6"]" />
        Academic Rank: <input type="text" name="searchARank" value="@ViewData["CurrentFilter7"]" />
        <input type="submit" value="Filter" />  |
        <a asp-action="Index"> Back to Full List</a>
    </p>
</form>


<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Degree)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AcademicRank)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OfficeNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HireDate)
            </th>
            <th>
                First Professor On
            </th>
            <th>
                Second Proffesor On
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
               <a asp-controller="Teachers" asp-action="GetTeacherById" asp-route-id="@item.Id"> @Html.DisplayFor(modelItem => item.FirstName) </a> <br/>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Degree)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AcademicRank)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OfficeNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HireDate)
            </td>
            <td>
                @if (item.FirstTeacherCourses != null)
                {
                    @foreach (var course in item.FirstTeacherCourses)
                    {
                        @if (course.Id != 0)
                        {
                            <a asp-controller="Courses" asp-action="Details" asp-route-id="@course.Id"> @course.Title</a> <br />
                        }
                    }
                }

            </td>
            <td>
                @if (item.SecondTeacherCourses != null)
                {
                    @foreach (var course in item.SecondTeacherCourses)
                    {
                        @if (course.Id != 0)
                        {
                            <a asp-controller="Courses" asp-action="Details" asp-route-id="@course.Id"> @course.Title </a> <br />
                        }
                    }
                }

            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
        }
    </tbody>
</table>